import Head from 'next/head'
import styles from '../styles/Home.module.css';
import Layout from '../components/common/layout';
import Settings_tabs from '../components/settingstabs'
import Ads from './ads';

export default function Home() {
 
  return (
    <>
      <Head>
        <title>VWeave</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="images/favicon.png" />
      </Head>
     
      {/* <UserManagementList /> */}
     {/* <Settings_tabs/> */}
     <Ads/>

    </>
  )
}
Home.getLayout = function getLayout(page) {
  
  return (
    <Layout>
      <div className="wrapper_body">
        {/* <div className="container"> */}
        {page}
        {/* </div> */}
      </div>
    </Layout>
  )
}
export async function getServerSideProps(context) {
  
  if (!context.req.cookies['Jwt-token']) {
    context.res.statusCode = 302
    context.res.setHeader('Location', `signin`)
  }
  return { props: {} }
}